---
- name: Ansible playbook interacting with 
  hosts: localhost
  connection: local
  
  vars:
      apod_url: "https://api.nasa.gov/planetary/apod?" # API to call
      mykey: "{{ lookup('file', '~/mycode/iss/nasa.key') }}"  # our api key
  
  vars_prompt:
    - name: date_
      prompt: date release version
      default: "2017-01-03"




  tasks:
  - name: Send HTTP GET to NASA api
    uri:
      method: GET     # send this method
      url: "{{ apod_url }}date={{date_}}&api_key={{ mykey }}"
    register: nasaread
    
  - name: Display the contents of the variable 'nasaread'
    debug:
      var: nasaread
      
  - name: Display just the explanation
    debug:
      var: nasaread.json.get('explanation')
      
  - name: Display just the HDURL
    debug:
      var: nasaread.json.get('hdurl',"No HD URL for today!")

