---
- name: Building Precheck Failures
  hosts: arista_witches_2        # group within the inventory to match on
  gather_facts: yes             # this defines ansible_facts
                                # (it runs *_facts on the target network switches)
  # best practice says this file will be searched for in a local vars/ folder
  vars_files:
    - ../vars/witchimagespec.yml

  tasks:
  # dig into the data we want to reveal
  - name: Getting at network interfaces
    debug:
     var: ansible_facts
     verbosity: 1

  # build a precheck condition where the playbook will FAIL if a condition is not met
  - name: "Precheck condition - Is switch running image {{ switch_image }}"
    fail:
      msg: "This switch does not appear to have the correct image loaded. Exiting..."
    when: ansible_facts.net_image != switch_image


  # build a precheck condition where the playbook will FAIL if a condition is not met
  - name: "Precheck condition - Is switch running image version {{ switch_image_version }}"
    fail:
      msg: "This switch does not appear to have the correct version of the firmware loaded. Exiting..."
    when: ansible_facts.net_version != switch_image_version

