---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ssh

  tasks:
   - name: make a directory
     file:
       path: ~/output/
       state: directory
   - name: shell wild
     shell: echo $HOME >> ~/output/path.txt
