- name: Push a script and run it
  hosts: localhost

  tasks:
    ## If you want your script to only evr execute once
    - script: /home/student/mycode/praybooks/Mod.py
      args:
        ## execute in python3 and only run if the following file is MISSING
        executable: python3
        creates: /home/student/mycode/stopper.txt
      register: results

    - debug:
        msg: "{{ results }}"

