---
- name: Network Agnostic Playbook 
  hosts: arista_witches_2
  gather_facts: no
  
  vars:
    ansible_ssh_pass: alta3
    dnsserver: "8.8.8.8"
  
  tasks: 
  - name: CONFIGURE DNS 
    cli_config: 
      config: ip name-server {{ dnsserver }}

  - name: CHECK CONFIGURATION 
    cli_command: 
      command: show run | i ip name-server 
    register: results 

  - name: PRINT OUTPUT TO SCREEN 
    debug: 
      var: results.stdout

